// LOGIN CONSTANTS
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'

// ADD ADMIN CONSTANTS
export const ADD_ADMIN_REQUEST = 'ADD_ADMIN_REQUEST'
export const ADD_ADMIN_SUCCESS = 'ADD_ADMIN_SUCCESS'
export const ADD_ADMIN_FAIL = 'ADD_ADMIN_FAIL'

// ADMIN OPERATIONS
export const GET_ANIMAL_REGISTRATIONS_REQUEST = 'GET_ANIMAL_REGISTRATIONS_REQUEST'
export const GET_ANIMAL_REGISTRATIONS_SUCCESS = 'GET_ANIMAL_REGISTRATIONS_SUCCESS'
export const GET_ANIMAL_REGISTRATIONS_FAIL = 'GET_ANIMAL_REGISTRATIONS_FAIL'

export const GET_PENDING_PETS_REQUEST = 'GET_PENDING_PETS_REQUEST'
export const GET_PENDING_PETS_SUCCESS = 'GET_PENDING_PETS_SUCCESS'
export const GET_PENDING_PETS_FAIL = 'GET_PENDING_PETS_FAIL'

export const GET_REGISTERED_PETS_REQUEST = 'GET_REGISTERED_PETS_REQUEST'
export const GET_REGISTERED_PETS_SUCCESS = 'GET_REGISTERED_PETS_SUCCESS'
export const GET_REGISTERED_PETS_FAIL = 'GET_REGISTERED_PETS_FAIL'

export const GET_NOTREGISTERED_PETS_REQUEST = 'GET_REGISTERED_PETS_REQUEST'
export const GET_NOTREGISTERED_PETS_SUCCESS = 'GET_REGISTERED_PETS_SUCCESS'
export const GET_NOTREGISTERED_PETS_FAIL = 'GET_NOTREGISTERED_PETS_FAIL'

export const DELETE_REGISTRATION_REQUEST = 'DELETE_REGISTRATION_REQUEST'
export const DELETE_REGISTRATION_SUCCESS = 'DELETE_REGISTRATION_SUCCESS'
export const DELETE_REGISTRATION_FAIL = 'DELETE_REGISTRATION_FAIL'

export const REGISTER_ANIMAL_REQUEST = 'REGISTER_ANIMAL_REQUEST'
export const REGISTER_ANIMAL_SUCCESS = 'REGISTER_ANIMAL_SUCCESS'
export const REGISTER_ANIMAL_FAIL = 'REGISTER_ANIMAL_FAIL'

export const SAVE_REQUIREMENTS_REQUEST = 'SAVE_REQUIREMENTS_REQUEST'
export const SAVE_REQUIREMENTS_SUCCESS = 'SAVE_REQUIREMENTS_SUCCESS'
export const SAVE_REQUIREMENTS_FAIL = 'SAVE_REQUIREMENTS_FAIL'

export const REJECT_REGISTRATION_REQUEST = 'REJECT_REGISTRATION_REQUEST'
export const REJECT_REGISTRATION_SUCCESS = 'REJECT_REGISTRATION_SUCCESS'
export const REJECT_REGISTRATION_FAIL = 'REJECT_REGISTRATION_FAIL'

export const GET_ADOPTIONS_REQUEST = 'GET_ADOPTIONS_REQUEST'
export const GET_ADOPTIONS_SUCCESS = 'GET_ADOPTIONS_SUCCESS'
export const GET_ADOPTIONS_FAIL = 'GET_ADOPTIONS_FAIL'

export const DELETE_ADOPTION_REQUEST = 'DELETE_ADOPTION_REQUEST'
export const DELETE_ADOPTION_SUCCESS = 'DELETE_ADOPTION_SUCCESS'
export const DELETE_ADOPTION_FAIL = 'DELETE_ADOPTION_FAIL'

// DONATIONS
export const GET_DONATIONS_REQUEST = 'GET_DONATIONS_REQUEST'
export const GET_DONATIONS_SUCCESS = 'GET_DONATIONS_SUCCESS'
export const GET_DONATIONS_FAIL = 'GET_DONATIONS_FAIL'

export const DELETE_DONATION_REQUEST = 'DELETE_DONATION_REQUEST'
export const DELETE_DONATION_SUCCESS = 'DELETE_DONATION_SUCCESS'
export const DELETE_DONATION_FAIL = 'DELETE_DONATION_FAIL'

export const RECEIVED_DONATION_REQUEST = 'RECEIVED_DONATION_REQUEST'
export const RECEIVED_DONATION_SUCCESS = 'RECEIVED_DONATION_SUCCESS'
export const RECEIVED_DONATION_FAIL = 'RECEIVED_DONATION_FAIL'

export const ADD_TO_INVENTORY_REQUEST = 'ADD_TO_INVENTORY_REQUEST'
export const ADD_TO_INVENTORY_SUCCESS = 'ADD_TO_INVENTORY_SUCCESS'
export const ADD_TO_INVENTORY_FAIL = 'ADD_TO_INVENTORY_FAIL'

export const GET_INVENTORY_REQUEST = 'GET_INVENTORY_REQUEST'
export const GET_INVENTORY_SUCCESS = 'GET_INVENTORY_SUCCESS'
export const GET_INVENTORY_FAIL = 'GET_INVENTORY_FAIL'

// ADOPTION APPLICATION
export const UPDATE_ADOPTION_APPLICATION_REQUEST = 'UPDATE_ADOPTION_APPLICATION_REQUEST'
export const UPDATE_ADOPTION_APPLICATION_SUCCESS = 'UPDATE_ADOPTION_APPLICATION_SUCCESS'
export const UPDATE_ADOPTION_APPLICATION_FAIL = 'UPDATE_ADOPTION_APPLICATION_FAIL'

export const GET_SPECIFIC_ADOPTION_REQUEST = 'GET_SPECIFIC_ADOPTION_REQUEST'
export const GET_SPECIFIC_ADOPTION_SUCCESS = 'GET_SPECIFIC_ADOPTION_SUCCESS'
export const GET_SPECIFIC_ADOPTION_FAIL = 'GET_SPECIFIC_ADOPTION_FAIL'

export const DELETE_ADMIN_ACCOUNT_REQUEST = 'DELETE_ADMIN_ACCOUNT_REQUEST'
export const DELETE_ADMIN_ACCOUNT_SUCCESS = 'DELETE_ADMIN_ACCOUNT_SUCCESS'
export const DELETE_ADMIN_ACCOUNT_FAIL = 'DELETE_ADMIN_ACCOUNT_FAIL'

export const HAS_BEEN_INTERVIEWED_REQUEST = 'HAS_BEEN_INTERVIEWED_REQUEST'
export const HAS_BEEN_INTERVIEWED_SUCCESS = 'HAS_BEEN_INTERVIEWED_SUCCESS'
export const HAS_BEEN_INTERVIEWED_FAIL = 'HAS_BEEN_INTERVIEWED_FAIL'

export const DELETE_USER_ACCOUNT_REQUEST = 'DELETE_USER_ACCOUNT_REQUEST'
export const DELETE_USER_ACCOUNT_SUCCESS = 'DELETE_USER_ACCOUNT_SUCCESS'
export const DELETE_USER_ACCOUNT_FAIL = 'DELETE_USER_ACCOUNT_FAIL'

export const GET_INTERVIEW_SCHED_REQUEST = 'GET_INTERVIEW_SCHED_REQUEST'
export const GET_INTERVIEW_SCHED_SUCCESS = 'GET_INTERVIEW_SCHED_SUCCESS'
export const GET_INTERVIEW_SCHED_FAIL = 'GET_INTERVIEW_SCHED_FAIL'

export const SEND_INTERVIEW_MESSAGE_REQUEST = 'SEND_INTERVIEW_MESSAGE_REQUEST'
export const SEND_INTERVIEW_MESSAGE_SUCCESS = 'SEND_INTERVIEW_MESSAGE_SUCCESS'
export const SEND_INTERVIEW_MESSAGE_FAIL = 'SEND_INTERVIEW_MESSAGE_FAIL'

// STRAY ANIMAL REPORTS
export const GET_STRAY_REPORTS_REQUEST = 'GET_STRAY_RERORTS_REQUEST'
export const GET_STRAY_REPORTS_SUCCESS = 'GET_STRAY_REPORTS_SUCCESS'
export const GET_STRAY_REPORTS_FAIL = 'GET_STRAY_REPORTS_FAIL'

export const GET_DISMISSED_REPORTS_REQUEST = 'GET_DISMISSED_REPORTS_REQUEST'
export const GET_DISMISSED_REPORTS_SUCCESS = 'GET_DISMISSED_REPORTS_SUCCESS'
export const GET_DISMISSED_REPORTS_FAIL = 'GET_DISMISSED_REPORTS_FAIL'

export const DISMISS_STRAY_REPORT_REQUEST = 'DISMISS_STRAY_REPORT_REQUEST'
export const DISMISS_STRAY_REPORT_SUCCESS = 'DISMISS_STRAY_REPORT_SUCCESS'
export const DISMISS_STRAY_REPORT_FAIL = 'DISMISS_STRAY_REPORT_FAIL'

export const DELETE_REPORT_REQUEST = 'DELETE_REPORT_REQUEST'
export const DELETE_REPORT_SUCCESS = 'DELETE_REPORT_SUCCESS'
export const DELETE_REPORT_FAIL = 'DELETE_REPORT_FAIL'

export const REPORT_VIEWED_REQUEST = 'REPORT_VIEWED_REQUEST'
export const REPORT_VIEWED_SUCCESS = 'REPORT_VIEWED_SUCCESS'
export const REPORT_VIEWED_FAIL = 'REPORT_VIEWED_FAIL'

// 
export const GET_FEEDBACKS_REQUEST = 'GET_FEEDBACKS_REQUEST'
export const GET_FEEDBACKS_SUCCESS = 'GET_FEEDBACKS_SUCCESS'
export const GET_FEEDBACKS_FAIL = 'GET_FEEDBACKS_FAIL'

export const GET_SPECFEEDBACK_REQUEST = 'GET_SPECFEEDBACK_REQUEST'
export const GET_SPECFEEDBACK_SUCCESS = 'GET_SPECFEEDBACK_SUCCESS'
export const GET_SPECFEEDBACK_FAIL = 'GET_SPECFEEDBACK_FAIL'

export const DELETE_FEEDBACK_REQUEST = 'DELETE_FEEDBACK_REQUEST'
export const DELETE_FEEDBACK_SUCCESS = 'DELETE_FEEDBACK_SUCCESS'
export const DELETE_FEEDBACK_FAIL = 'DELETE_FEEDBACK_FAIL'

export const FEEDBACK_VIEWED_REQUEST = 'FEEDBACK_VIEWED_REQUEST'
export const FEEDBACK_VIEWED_SUCCESS = 'FEEDBACK_VIEWED_SUCCESS'
export const FEEDBACK_VIEWED_FAIL = 'FEEDBACK_VIEWED_FAIL'