export const ANIMAL_DATA_REQUEST = 'ANIMAL_DATA_REQUEST'
export const ANIMAL_DATA_SUCCESS = 'ANIMAL_DATA_SUCCESS'
export const ANIMAL_DATA_FAIL = 'ANIMAL_DATA_FAIL'

export const ANIMAL_CREATE_REQUEST = 'ANIMAL_CREATE_REQUEST'
export const ANIMAL_CREATE_SUCCESS = 'ANIMAL_CREATE_SUCCESS'
export const ANIMAL_CREATE_FAIL = 'ANIMAL_CREATE_FAIL'

export const ANIMAL_UPDATE_REQUEST = 'ANIMAL_UPDATE_REQUEST'
export const ANIMAL_UPDATE_SUCCESS = 'ANIMAL_UPDATE_SUCCESS'
export const ANIMAL_UPDATE_FAIL = 'ANIMAL_UPDATE_FAIL'

export const ANIMAL_DELETE_REQUEST = 'ANIMAL_DELETE_REQUEST'
export const ANIMAL_DELETE_SUCCESS = 'ANIMAL_DELETE_SUCCESS'
export const ANIMAL_DELETE_FAIL = 'ANIMAL_DELETE_FAIL'
